version = 0.1
[default.deploy.parameters]
stack_name = "perspeak-enquiry-api"
resolve_s3 = true
s3_prefix = "perspeak-enquiry-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Stage=\"staging\" Region=\"us-east-1\""
